### PR TITLE
Added Japanese translations

### PR DESCRIPTION
**Pull request by kuragehimekurara1**

### CODE REVIEW

**Comment by henkelmax** [comment]
I can't find the language code `ja_ryu` anywhere. Are you sure thats an actual language Minecraft supports?

**Review by henkelmax — CHANGES_REQUESTED** [review]
`ja_ryu` does not seem to be a valid language code

**Comment by kuragehimekurara1** [comment]
Sorry for the late response. Deleted ja_ryu files.

**Review by henkelmax — APPROVED** [review]

**Comment by henkelmax** [comment]
Thank you!

**Pull request merged**
